/** The shipped native consumer surface. This declaration is not deployment or activation evidence. */
export const ratingScopedNativeRoutes = Object.freeze(
  [
    ['CreateContext', 'POST', '/v2/ratings/contexts'],
    ['ResolveLocator', 'POST', '/v2/ratings/locators/resolve'],
    ['ListCategories', 'GET', '/v2/ratings/categories'],
    ['ListTargets', 'GET', '/v2/ratings/targets'],
    ['GetTarget', 'GET', '/v2/ratings/targets/:id'],
    ['GetMyScore', 'GET', '/v2/ratings/targets/:id/my-score'],
    ['GetScoreSummary', 'GET', '/v2/ratings/targets/:id/score-summary'],
    ['ListComments', 'GET', '/v2/ratings/targets/:id/comments'],
    ['GetComment', 'GET', '/v2/ratings/comments/:id'],
    ['GetDiscussion', 'GET', '/v2/ratings/comments/:id/discussion'],
    ['ListReplies', 'GET', '/v2/ratings/comments/:id/replies'],
    ['GetReply', 'GET', '/v2/ratings/replies/:id'],
    ['GetReplyPosition', 'GET', '/v2/ratings/replies/:id/position'],
    ['GetCommentLike', 'GET', '/v2/ratings/comments/:id/like'],
    ['GetReplyLike', 'GET', '/v2/ratings/replies/:id/like'],
    ['GetSubscription', 'GET', '/v2/ratings/targets/:id/subscription'],
    [
      'QuerySubscriptionStates',
      'POST',
      '/v2/ratings/subscription-states/query',
    ],
    ['ListSubscriptions', 'GET', '/v2/ratings/subscriptions'],
    ['GetRandomTarget', 'GET', '/v2/ratings/random-target'],
    ['SetScore', 'PUT', '/v2/ratings/targets/:id/my-score'],
    ['SetCommentLike', 'PUT', '/v2/ratings/comments/:id/like'],
    ['SetReplyLike', 'PUT', '/v2/ratings/replies/:id/like'],
    ['SetSubscription', 'PUT', '/v2/ratings/targets/:id/subscription'],
    ['CreateComment', 'POST', '/v2/ratings/targets/:id/comments'],
    ['CreateReply', 'POST', '/v2/ratings/comments/:id/replies'],
    ['PrepareTarget', 'POST', '/v2/ratings/management/prepare'],
    ['CreateTarget', 'POST', '/v2/ratings/management/targets'],
    ['CancelTargetCreation', 'POST', '/v2/ratings/management/cancel'],
    [
      'GetEditContext',
      'GET',
      '/v2/ratings/management/owner-edit/targets/:targetId/context',
    ],
    ['PrepareTargetEdit', 'POST', '/v2/ratings/management/owner-edit/prepare'],
    ['CommitTargetEdit', 'POST', '/v2/ratings/management/owner-edit/commit'],
    ['CancelTargetEdit', 'POST', '/v2/ratings/management/owner-edit/cancel'],
    ['GetRequest', 'GET', '/v2/ratings/requests/:requestId'],
    ['ListUpdates', 'GET', '/v2/me/ratings/updates'],
    ['ResolveUpdateTarget', 'GET', '/v2/me/ratings/updates/:noticeId/target'],
    ['ListLikeUpdates', 'GET', '/v2/me/ratings/like-updates'],
    [
      'ResolveLikeUpdateTarget',
      'GET',
      '/v2/me/ratings/like-updates/:noticeId/target',
    ],
    ['ListSubscriptionUpdates', 'GET', '/v2/me/ratings/subscription-updates'],
    [
      'ResolveSubscriptionUpdateTarget',
      'GET',
      '/v2/me/ratings/subscription-updates/:noticeId/target',
    ],
  ].map(([name, method, path]) =>
    Object.freeze({
      operationId: `ratingScoped${name}`,
      method: method!,
      path: path!,
    }),
  ),
);
